language: php

matrix:
  include:
    - php: 5.6

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - cp app/config/parameters.yml.dist app/config/parameters.yml

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - composer install --no-progress --no-interaction  --dev

script:
  - php bin/phpspec run --no-code-generation --stop-on-failure
  - php bin/phpunit 

