trolley_agenda:
    resource: "@TrolleyAgendaBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

startpage:
    path: /
    defaults: { _controller: TrolleyAgendaBundle:Calendar:index }