<?php

namespace Trolley\AgendaBundle\Repository;

/**
 * DayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Holt aus der DB die Passende Tagen
     *
     * @param array $Days
     *
     * @return array
     */
    public function findDaysByDate(array $Days)
    {
        $qB = $this->createQueryBuilder('d');

        $qB->where(
            $qB->expr()->in('DATE_FORMAT(d.taDay, \'%Y-%m-%d\')', $Days)
        );

        return $qB->getQuery()->getResult();
    }
}
