<?php

namespace Trolley\AgendaBundle\Repository;

/**
 * HistoryServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
