<?php

namespace Trolley\AgendaBundle\Repository;

/**
 * RouteDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Findet die Default route
     */
    public function findDefaultRoute()
    {
        $qB = $this->createQueryBuilder('r')
            ->select('r.id')
            ->setMaxResults(1);

        $query = $qB->getQuery();

        $query->useQueryCache(true);
        $query->useResultCache(true, 60*60*24);

        $result = $query->getResult();
        if (empty($result)) {
            return null;
        }

        $firstElement = array_shift($result);

        return $firstElement['id'];
    }
}
