<?php

namespace Trolley\AgendaBundle\Repository;

/**
 * RouteDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
