<?php

namespace Trolley\AgendaBundle\Repository;

use Symfony\Component\VarDumper\VarDumper;

/**
 * UserAutocompleteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAutocompleteFirstlastname($name)
    {
        $qB = $this->createQueryBuilder('u')
            ->select('u.id, u.firstlastname AS text')
            ->where('u.firstlastname LIKE ?1')
            ->andWhere('u.enabled = 1')
            ->setParameter('1', '%'.$name.'%');

        return $qB->getQuery()->getResult();
    }
}
